"""add notification delivery retries

Revision ID: 81944cbe44fa
Revises: 39153dc5aef5
Create Date: 2026-09-22 14:42:08.387981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81944cbe44fa'
down_revision = '39153dc5aef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('provider_message_id', sa.String(length=180), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.drop_column('provider_message_id')
        batch_op.drop_column('next_attempt_at')
        batch_op.drop_column('attempt_count')

    # ### end Alembic commands ###
