import { useState } from 'react'
import AppShell from '../components/AppShell'
import { createDesignBrief, uploadDesignRoomImage } from '../lib/api'

export default function AIDesignAssistantPage() {
  const [form, setForm] = useState({ room: 'Living room', style: 'Warm modern', material: 'Walnut', color: 'Sand', budget: 150000, image_url: '' })
  const [brief, setBrief] = useState(null); const [loading, setLoading] = useState(false); const [uploading, setUploading] = useState(false); const [error, setError] = useState('')
  async function uploadImage(event) { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setError(''); try { const result = await uploadDesignRoomImage(file); setForm((current) => ({ ...current, image_url: result.item.url })) } catch (err) { setError(err.message) } finally { setUploading(false) } }
  async function submit(event) { event.preventDefault(); setLoading(true); setError(''); try { setBrief((await createDesignBrief(form)).brief) } catch (err) { setError(err.message) } finally { setLoading(false) } }
  return <AppShell title="AI design assistant" eyebrow="Room brief, moodboard & product direction"><div className="design-layout"><section className="panel"><form className="service-form" onSubmit={submit}><label>Room<input value={form.room} onChange={(e) => setForm({ ...form, room: e.target.value })} /></label><label>Style<input value={form.style} onChange={(e) => setForm({ ...form, style: e.target.value })} /></label><label>Material<input value={form.material} onChange={(e) => setForm({ ...form, material: e.target.value })} /></label><label>Accent color<input value={form.color} onChange={(e) => setForm({ ...form, color: e.target.value })} /></label><label>Budget<input type="number" value={form.budget} onChange={(e) => setForm({ ...form, budget: e.target.value })} /></label><label>Room image <small className="field-hint">Upload a JPG, PNG or WEBP; demo mode works without an API.</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={uploadImage} />{form.image_url && <small className="field-hint">Image ready for analysis.</small>}</label><label>Image URL <input value={form.image_url} onChange={(e) => setForm({ ...form, image_url: e.target.value })} /></label><button className="button" disabled={loading || uploading}>{uploading ? 'Uploading image…' : loading ? 'Creating brief…' : 'Create design brief'}</button>{error && <div className="form-error">{error}</div>}</form></section>{brief && <section className="panel"><div className="panel-heading"><div><p className="eyebrow">{brief.provider}</p><h3>{brief.title}</h3></div><span className="tag">{brief.confidence || 'AI'}</span></div><h4>Layout</h4><ul>{(brief.layout || []).map((item) => <li key={item}>{item}</li>)}</ul><h4>Moodboard</h4><div className="tag-list">{(brief.moodboard || []).map((item, index) => <span className="tag" key={index}>{item.label}: {item.value}</span>)}</div><h4>Recommended next steps</h4><ul>{(brief.next_steps || []).map((item) => <li key={item}>{item}</li>)}</ul><h4>Recommended products</h4>{(brief.recommendations || []).map((item) => <div className="order-meta" key={item.product?.id}><span><strong>{item.product?.name}</strong><small>{item.reason}</small></span><b>₹{Number(item.product?.price || 0).toLocaleString('en-IN')}</b></div>)}</section>}</div></AppShell>
}
