import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { getAnalytics } from '../lib/api'

const money = (value) => `INR ${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 0 })}`

export default function AnalyticsPage() {
  const [data, setData] = useState(null); const [error, setError] = useState('')
  useEffect(() => { getAnalytics().then(setData).catch((err) => setError(err.message)) }, [])
  if (error) return <AppShell title="Analytics & forecasting" eyebrow="Revenue, pipeline & operations"><div className="form-error">{error}</div></AppShell>
  if (!data) return <AppShell title="Analytics & forecasting" eyebrow="Revenue, pipeline & operations"><p className="muted-copy">Loading analytics…</p></AppShell>
  const summary = data.summary || {}
  return <AppShell title="Analytics & forecasting" eyebrow="Revenue, pipeline & operations"><section className="analytics-metrics">{[['Collected revenue', money(summary.revenue)], ['Outstanding', money(summary.outstanding)], ['Open pipeline', money(summary.quote_pipeline)], ['Quote conversion', `${summary.conversion_rate}%`], ['Inventory value', money(summary.inventory_value)], ['Low-stock items', summary.low_stock]].map(([label, value]) => <article className="panel analytics-metric" key={label}><p className="eyebrow">{label}</p><strong>{value}</strong></article>)}</section><div className="analytics-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Forecast</p><h3>Weighted revenue outlook</h3></div></div><div className="forecast-grid"><div><span>Next 30 days</span><strong>{money(data.forecast?.next_30_days)}</strong></div><div><span>Next 90 days</span><strong>{money(data.forecast?.next_90_days)}</strong></div></div><p className="muted-copy">{data.forecast?.method}</p></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Customer value</p><h3>Top customers</h3></div></div>{(data.top_customers || []).map((item) => <div className="analytics-row" key={item.customer}><span>{item.customer}</span><strong>{money(item.value)}</strong></div>)}</section></div><div className="analytics-grid"><section className="panel"><p className="eyebrow">Quotes</p><h3>Pipeline mix</h3><div className="analytics-bars">{(data.quotes_by_status || []).map((item) => <div key={item.label}><span>{item.label}</span><b style={{ width: `${Math.max(item.count * 25, 12)}%` }}>{item.count}</b></div>)}</div></section><section className="panel"><p className="eyebrow">Operations</p><h3>Workload snapshots</h3><div className="analytics-subgrid"><div><strong>{summary.lead_win_rate}%</strong><span>lead win rate</span></div><div><strong>{(data.production_by_status || []).reduce((sum, item) => sum + item.count, 0)}</strong><span>production jobs</span></div></div>{(data.production_by_status || []).map((item) => <div className="analytics-row" key={item.label}><span>{item.label}</span><strong>{item.count}</strong></div>)}</section></div></AppShell>
}
