import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { getAuditLogs } from '../lib/api'

export default function AuditPage() {
  const [logs, setLogs] = useState([]); const [summary, setSummary] = useState({ total: 0, resources: {}, actions: {}, last_activity: null }); const [resource, setResource] = useState(''); const [action, setAction] = useState(''); const [error, setError] = useState('')
  async function load() { try { const result = await getAuditLogs(resource, action); setLogs(result.items || []); setSummary(result.summary || { total: 0, resources: {}, actions: {}, last_activity: null }); setError('') } catch (err) { setError(err.message) } }
  useEffect(() => { load() }, [resource, action])
  const topResources = Object.entries(summary.resources || {}).sort((a, b) => b[1] - a[1]).slice(0, 4)
  return <AppShell title="Audit dashboard" eyebrow="Security & accountability"><div className="metric-grid"><article className="metric-card"><span>Total events</span><strong>{summary.total}</strong><small>Showing the latest filtered activity</small></article><article className="metric-card"><span>Resource types</span><strong>{Object.keys(summary.resources || {}).length}</strong><small>Areas with recorded changes</small></article><article className="metric-card"><span>Action types</span><strong>{Object.keys(summary.actions || {}).length}</strong><small>Distinct operations recorded</small></article><article className="metric-card"><span>Last activity</span><strong>{summary.last_activity ? new Date(summary.last_activity).toLocaleDateString() : '—'}</strong><small>{summary.last_activity ? new Date(summary.last_activity).toLocaleTimeString() : 'No activity yet'}</small></article></div><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Admin monitoring</p><h3>Activity overview</h3></div><div className="audit-breakdown">{topResources.map(([name, count]) => <span className="tag" key={name}>{name}: {count}</span>)}</div></div><div className="toolbar"><select value={resource} onChange={(e) => setResource(e.target.value)}><option value="">All resources</option><option value="quote">Quotes</option><option value="invoice">Invoices</option><option value="inventory">Inventory</option><option value="purchase_order">Purchase orders</option><option value="notification">Notifications</option><option value="user">Users</option></select><select value={action} onChange={(e) => setAction(e.target.value)}><option value="">All actions</option>{Object.keys(summary.actions || {}).sort().map((item) => <option key={item} value={item}>{item}</option>)}</select></div></section><section className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>When</th><th>User</th><th>Action</th><th>Resource</th><th>Detail</th></tr></thead><tbody>{logs.map((item) => <tr key={item.id}><td data-label="When">{new Date(item.created_at).toLocaleString()}</td><td data-label="User">{item.user?.name || 'System'}</td><td data-label="Action"><strong>{item.action}</strong></td><td data-label="Resource">{item.resource_type} {item.resource_id}</td><td data-label="Detail">{item.detail || '—'}</td></tr>)}</tbody></table>{!logs.length && <p className="empty-state">No audit events match the selected filters.</p>}</div></section>{error && <div className="form-error">{error}</div>}</AppShell>
}
