import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { assignBranchUser, createBranch, getAccessUsers, getBranches } from '../lib/api'

export default function BranchSecurityPage() {
  const [branches, setBranches] = useState([]); const [users, setUsers] = useState([]); const [form, setForm] = useState({ name: '', code: '', address: '', manager: '' }); const [selected, setSelected] = useState(''); const [userId, setUserId] = useState(''); const [message, setMessage] = useState('')
  async function load() { const [branchResult, userResult] = await Promise.all([getBranches(), getAccessUsers()]); setBranches(branchResult.items || []); setUsers((userResult.items || []).map((item) => item.user || item)) }
  useEffect(() => { load() }, [])
  async function addBranch(event) { event.preventDefault(); await createBranch(form); setForm({ name: '', code: '', address: '', manager: '' }); setMessage('Branch created.'); await load() }
  async function assign(event) { event.preventDefault(); if (!selected || !userId) return; await assignBranchUser(selected, { user_id: Number(userId), is_primary: true }); setMessage('User assigned to branch.') }
  return <AppShell title="Branches & security" eyebrow="Multi-branch access boundaries"><div className="service-layout"><section className="panel"><div className="panel-heading"><h3>New branch</h3></div><form className="mini-form" onSubmit={addBranch}><input required placeholder="Branch name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><input required placeholder="Code e.g. DEL" value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value })} /><input placeholder="Address" value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} /><input placeholder="Manager" value={form.manager} onChange={(event) => setForm({ ...form, manager: event.target.value })} /><button className="button">Create branch</button></form></section><section className="panel"><div className="panel-heading"><h3>Assign user</h3></div><form className="mini-form" onSubmit={assign}><select required value={selected} onChange={(event) => setSelected(event.target.value)}><option value="">Choose branch</option>{branches.map((item) => <option key={item.id} value={item.id}>{item.name} ({item.code})</option>)}</select><select required value={userId} onChange={(event) => setUserId(event.target.value)}><option value="">Choose user</option>{users.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.role}</option>)}</select><button className="button">Assign user</button></form></section></div><section className="supplier-grid">{branches.map((item) => <article className="panel supplier-card" key={item.id}><p className="eyebrow">Branch {item.code}</p><h3>{item.name}</h3><p>{item.address || 'Address not set'} · {item.manager || 'Manager not set'}</p></article>)}</section>{message && <div className="success-message">{message}</div>}</AppShell>
}
