import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { createContract, downloadContractPdf, getClientQuotes, getContracts, getQuotes, signContract, updateContract } from '../lib/api'
import { useAuth } from '../context/AuthContext'

const defaultTerms = '1. Furnivo will deliver the approved scope and materials listed in the quotation.\n2. Production begins after written approval and agreed advance payment.\n3. Delivery and installation dates are scheduled after material confirmation.\n4. Variations require written approval and may change price or timeline.'

export default function ContractsPage() {
  const { user } = useAuth(); const canManage = ['admin', 'sales', 'designer'].includes(user.role); const [items, setItems] = useState([]); const [quotes, setQuotes] = useState([]); const [showForm, setShowForm] = useState(false); const [error, setError] = useState(''); const [signature, setSignature] = useState({}); const [form, setForm] = useState({ quote_id: '', title: '', terms: defaultTerms })
  async function load() { const contracts = await getContracts(); setItems(contracts.items || []); if (canManage) setQuotes((await getQuotes()).items || []); else setQuotes((await getClientQuotes()).items || []) }
  useEffect(() => { load().catch((err) => setError(err.message)) }, [])
  async function submit(event) { event.preventDefault(); try { await createContract(form); setShowForm(false); setForm({ quote_id: '', title: '', terms: defaultTerms }); await load() } catch (err) { setError(err.message) } }
  async function sign(item) { if (!signature[item.id]?.trim()) return setError('Enter your full name as the signature.'); try { await signContract(item.id, signature[item.id]); await load() } catch (err) { setError(err.message) } }
  async function status(item, value) { try { await updateContract(item.id, { status: value }); await load() } catch (err) { setError(err.message) } }
  return <AppShell title="Contracts & e-signatures" eyebrow="Terms, approvals & locked versions" actions={canManage && <button className="button button-small" onClick={() => setShowForm(!showForm)}>{showForm ? 'Close' : 'New contract'}</button>}>
    {showForm && <form className="panel customer-editor" onSubmit={submit}><h3>Create contract from quotation</h3><div className="form-grid form-grid-3"><label>Quotation<select required value={form.quote_id} onChange={(e) => setForm({ ...form, quote_id: e.target.value })}><option value="">Choose quotation</option>{quotes.map((quote) => <option value={quote.database_id || quote.id} key={quote.database_id || quote.id}>{quote.id} · {quote.customer}</option>)}</select></label><label>Contract title<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Project agreement" /></label><label className="form-span-3">Terms<textarea rows="6" required value={form.terms} onChange={(e) => setForm({ ...form, terms: e.target.value })} /></label></div>{error && <div className="form-error">{error}</div>}<button className="button">Send contract</button></form>}
    {error && !showForm && <div className="form-error">{error}</div>}<section className="contract-grid">{items.map((item) => <article className="panel contract-card" key={item.id}><div className="panel-heading"><div><p className="eyebrow">{item.contract_number} · {item.quote_number}</p><h3>{item.customer}</h3></div>{canManage && !item.locked ? <select value={item.status} onChange={(e) => status(item, e.target.value)}><option>Draft</option><option>Sent</option><option>Voided</option></select> : <span className={`status status-${item.status.toLowerCase()}`}>{item.status}</span>}</div><h4>{item.title}</h4><p className="contract-terms">{item.terms}</p><div className="contract-signatures">{item.signatures?.length ? item.signatures.map((entry) => <small key={entry.id}>Signed by {entry.signer_name} as {entry.signature_text} · {new Date(entry.signed_at).toLocaleDateString()}</small>) : <small>Awaiting signature</small>}</div><div className="card-actions"><button className="button-link" onClick={() => downloadContractPdf(item)}>Download contract</button>{user.role === 'client' && !item.locked && <><input className="signature-input" placeholder="Type full name to sign" value={signature[item.id] || ''} onChange={(e) => setSignature({ ...signature, [item.id]: e.target.value })} /><button className="button button-small" onClick={() => sign(item)}>Sign contract</button></>}</div></article>)}</section>
  </AppShell>
}
