import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { getCustomReport } from '../lib/api'

const catalog = [['quotes', 'Quotes'], ['leads', 'Leads'], ['orders', 'Orders'], ['invoices', 'Invoices'], ['payments', 'Payments'], ['inventory', 'Inventory'], ['profitability', 'Profitability'], ['forecast', 'Forecast']]

export default function CustomReportsPage() {
  const [selected, setSelected] = useState(['quotes', 'orders', 'invoices', 'inventory']); const [period, setPeriod] = useState(90); const [report, setReport] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  async function load() { setLoading(true); setError(''); try { setReport((await getCustomReport(selected, period)).report) } catch (err) { setError(err.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  function toggle(key) { setSelected((items) => items.includes(key) ? items.filter((item) => item !== key) : [...items, key]) }
  function exportCsv() { if (!report) return; const rows = [['Metric', 'Data'], ...Object.entries(report.metrics || {}).map(([key, value]) => [key, JSON.stringify(value)])]; const csv = rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `furnivo-custom-report-${report.period_days}d.csv`; anchor.click(); URL.revokeObjectURL(url) }
  return <AppShell title="Custom reports & business intelligence" eyebrow="KPI dashboards, profitability & forecasts" actions={<button className="button button-small" onClick={exportCsv} disabled={!report}>Export CSV</button>}><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Report builder</p><h3>Select management metrics</h3></div><span className="tag">{loading ? 'Refreshing…' : report?.filters?.scope || 'Workspace'}</span></div><div className="tag-list">{catalog.map(([key, label]) => <label className="tag" key={key}><input type="checkbox" checked={selected.includes(key)} onChange={() => toggle(key)} /> {label}</label>)}</div><div className="mini-form"><label>Period<select value={period} onChange={(event) => setPeriod(Number(event.target.value))}><option value="30">30 days</option><option value="90">90 days</option><option value="180">180 days</option><option value="365">365 days</option></select></label><button className="button" onClick={load} disabled={!selected.length || loading}>Run report</button></div><p className="muted-copy">Exports are generated from the current workspace and support CSV now; PDF/XLSX adapters are ready for deployment integration.</p></section>{error && <div className="form-error">{error}</div>}{report && <section className="report-grid">{Object.entries(report.metrics || {}).map(([key, data]) => { const label = catalog.find(([metric]) => metric === key)?.[1] || key; const count = data.count ?? data.items ?? ''; const value = data.value ?? data.revenue ?? data.gross_profit ?? data.next_30_days; return <article className="panel report-card" key={key}><p className="eyebrow">{label}</p><strong>{typeof count === 'number' ? count : value != null ? `₹${Number(value).toLocaleString('en-IN')}` : '—'}</strong><span>{data.margin_percent != null ? `${data.margin_percent}% margin` : data.balance != null ? `₹${Number(data.balance).toLocaleString('en-IN')} outstanding` : data.low_stock != null ? `${data.low_stock} low-stock items` : data.confidence_percent != null ? `${data.confidence_percent}% forecast confidence` : data.won != null ? `${data.won} won` : 'Workspace metric'}</span></article> })}</section>}</AppShell>
}
