import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { createBackgroundJob, getBackgroundJobs, getCustomers, getProducts, importCustomersCsv, importProductsCsv } from '../lib/api'

export default function DataAdminPage() {
  const [products, setProducts] = useState([]); const [customers, setCustomers] = useState([]); const [jobs, setJobs] = useState([]); const [query, setQuery] = useState(''); const [includeArchived, setIncludeArchived] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  async function load() { const options = { q: query, page: 1, page_size: 20, include_archived: String(includeArchived) }; const [productResult, customerResult, jobResult] = await Promise.all([getProducts(options), getCustomers(options), getBackgroundJobs()]); setProducts(productResult.items || []); setCustomers(customerResult.items || []); setJobs(jobResult.items || []) }
  useEffect(() => { load().catch((err) => setError(err.message)) }, [includeArchived])
  async function search(event) { event.preventDefault(); try { await load() } catch (err) { setError(err.message) } }
  async function importFile(event, importer) { const file = event.target.files?.[0]; if (!file) return; try { const result = await importer(file); setMessage(`Import complete: ${result.created || 0} created, ${result.updated || 0} updated, ${result.errors || 0} errors.`); await load() } catch (err) { setError(err.message) } finally { event.target.value = '' } }
  async function runJob(type) { try { await createBackgroundJob(type); setMessage(`${type} queued.`); await load() } catch (err) { setError(err.message) } }
  return <AppShell title="Data administration" eyebrow="Search, import & background jobs"><form className="panel data-search" onSubmit={search}><div className="panel-heading"><div><p className="eyebrow">Large dataset controls</p><h3>Search catalog and customers</h3></div><label className="archive-toggle"><input type="checkbox" checked={includeArchived} onChange={(e) => setIncludeArchived(e.target.checked)} /> Include archived</label></div><div className="mini-form"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search names, SKU, company or email" /><button className="button button-small">Search</button></div></form>{(error || message) && <div className={error ? 'form-error' : 'success-message'}>{error || message}</div>}<section className="data-admin-grid"><article className="panel"><div className="panel-heading"><h3>Catalog records</h3><span>{products.length} loaded</span></div>{products.map((item) => <div className="data-row" key={item.id}><span><strong>{item.name}</strong><small>{item.sku} · {item.category}</small></span><b>{item.is_active === false ? 'Archived' : `₹${Number(item.price || 0).toLocaleString('en-IN')}`}</b></div>)}</article><article className="panel"><div className="panel-heading"><h3>Customer records</h3><span>{customers.length} loaded</span></div>{customers.map((item) => <div className="data-row" key={item.id}><span><strong>{item.company}</strong><small>{item.contact_name} · {item.email}</small></span><b>{item.is_active === false ? 'Archived' : 'Active'}</b></div>)}</article></section><section className="panel import-panel"><div className="panel-heading"><div><p className="eyebrow">Bulk import</p><h3>CSV administration</h3></div></div><p className="muted-copy">Products: sku, name, category, price, unit, material, description, is_active. Customers: company, contact_name, email, phone, billing_address, project_address, gstin, notes.</p><div className="card-actions"><label className="button button-ghost file-button">Import products CSV<input type="file" accept=".csv,text/csv" onChange={(e) => importFile(e, importProductsCsv)} /></label><label className="button button-ghost file-button">Import customers CSV<input type="file" accept=".csv,text/csv" onChange={(e) => importFile(e, importCustomersCsv)} /></label></div></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Async work</p><h3>Background jobs</h3></div><div className="card-actions"><button className="button-link" onClick={() => runJob('catalog-reindex')}>Reindex catalog</button><button className="button-link" onClick={() => runJob('report-refresh')}>Refresh reports</button></div></div>{jobs.map((job) => <div className="data-row" key={job.id}><span><strong>{job.job_type}</strong><small>{new Date(job.created_at).toLocaleString()}</small></span><b>{job.status}</b></div>)}</section></AppShell>
}
