import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { generateEInvoice, generateEwayBill, getEInvoices, getInvoices } from '../lib/api'

export default function GstPage() {
  const [items, setItems] = useState([]); const [invoices, setInvoices] = useState([]); const [showForm, setShowForm] = useState(false); const [error, setError] = useState(''); const [form, setForm] = useState({ invoice_id: '', gstin: '', place_of_supply: 'Delhi', tax_mode: 'CGST/SGST', hsn: '9403' })
  async function load() { const [eInvoiceResult, invoiceResult] = await Promise.all([getEInvoices(), getInvoices()]); setItems(eInvoiceResult.items || []); setInvoices(invoiceResult.items || []) }
  useEffect(() => { load().catch((err) => setError(err.message)) }, [])
  async function submit(event) { event.preventDefault(); try { await generateEInvoice(form.invoice_id, { gstin: form.gstin, place_of_supply: form.place_of_supply, tax_mode: form.tax_mode, hsn_summary: [{ hsn: form.hsn, description: 'Furniture and interiors' }] }); setShowForm(false); await load() } catch (err) { setError(err.message) } }
  async function eway(item) { try { await generateEwayBill(item.id); await load() } catch (err) { setError(err.message) } }
  return <AppShell title="GST & e-invoicing" eyebrow="Tax documents & compliance" actions={<button className="button button-small" onClick={() => setShowForm(!showForm)}>{showForm ? 'Close' : 'Generate e-invoice'}</button>}>
    {showForm && <form className="panel customer-editor" onSubmit={submit}><h3>Generate e-invoice</h3><div className="form-grid form-grid-3"><label>Invoice<select required value={form.invoice_id} onChange={(e) => setForm({ ...form, invoice_id: e.target.value })}><option value="">Choose invoice</option>{invoices.map((invoice) => <option value={invoice.id} key={invoice.id}>{invoice.invoice_number} · {invoice.customer}</option>)}</select></label><label>Customer GSTIN<input value={form.gstin} onChange={(e) => setForm({ ...form, gstin: e.target.value })} placeholder="07ABCDE1234F1Z5" /></label><label>Place of supply<input value={form.place_of_supply} onChange={(e) => setForm({ ...form, place_of_supply: e.target.value })} /></label><label>Tax mode<select value={form.tax_mode} onChange={(e) => setForm({ ...form, tax_mode: e.target.value })}><option>CGST/SGST</option><option>IGST</option></select></label><label>HSN / SAC<input value={form.hsn} onChange={(e) => setForm({ ...form, hsn: e.target.value })} /></label></div>{error && <div className="form-error">{error}</div>}<button className="button">Generate IRN record</button></form>}
    {error && !showForm && <div className="form-error">{error}</div>}<section className="gst-grid">{items.map((item) => <article className="panel gst-card" key={item.id}><div className="panel-heading"><div><p className="eyebrow">{item.invoice_number} · {item.tax_mode}</p><h3>{item.customer}</h3></div><span className="status status-approved">{item.status}</span></div><div className="gst-meta"><span>GSTIN<strong>{item.gstin || 'Not provided'}</strong></span><span>Place<strong>{item.place_of_supply || '—'}</strong></span></div><div className="gst-tax-grid"><div>CGST<strong>₹{Number(item.cgst_amount || 0).toLocaleString('en-IN')}</strong></div><div>SGST<strong>₹{Number(item.sgst_amount || 0).toLocaleString('en-IN')}</strong></div><div>IGST<strong>₹{Number(item.igst_amount || 0).toLocaleString('en-IN')}</strong></div></div><p className="gst-irn">IRN: {item.irn}<br />Ack: {item.acknowledgement_number}</p><div className="card-actions">{item.eway_bill_number ? <span className="status status-approved">{item.eway_bill_number}</span> : <button className="button button-ghost button-small" onClick={() => eway(item)}>Generate e-way bill</button>}</div></article>)}</section>
  </AppShell>
}
