import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { createIntegration, getIntegrations, syncIntegration, updateIntegration } from '../lib/api'

export default function IntegrationsPage() {
  const [connections, setConnections] = useState([]); const [runs, setRuns] = useState([]); const [form, setForm] = useState({ name: '', provider: 'Zoho Books', external_account: '', credentials_ref: '' }); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  async function load() { const result = await getIntegrations(); setConnections(result.connections || []); setRuns(result.runs || []) }
  useEffect(() => { load().catch((err) => setError(err.message)) }, [])
  async function submit(event) { event.preventDefault(); try { const result = await createIntegration(form); setConnections((items) => [...items, result.item]); setForm({ name: '', provider: 'Zoho Books', external_account: '', credentials_ref: '' }); setMessage('Integration connected.'); setError('') } catch (err) { setError(err.message) } }
  async function sync(item) { try { const result = await syncIntegration(item.id, 'invoices'); setConnections((items) => items.map((entry) => entry.id === item.id ? result.connection : entry)); setRuns((items) => [result.item, ...items]); setMessage(`${item.provider} sync completed.`) } catch (err) { setError(err.message) } }
  async function toggle(item) { const result = await updateIntegration(item.id, { is_enabled: !item.is_enabled }); setConnections((items) => items.map((entry) => entry.id === item.id ? result.item : entry)) }
  return <AppShell title="Accounting & ERP integrations" eyebrow="Tally, Zoho Books & QuickBooks"><section className="integration-layout"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Connect provider</p><h3>Secure accounting link</h3></div></div><p className="muted-copy">Store only an environment/secret reference here. Provider credentials never enter browser local storage.</p><form className="integration-form" onSubmit={submit}><label>Connection name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Provider<select value={form.provider} onChange={(event) => setForm({ ...form, provider: event.target.value })}><option>Tally</option><option>Zoho Books</option><option>QuickBooks</option></select></label><label>External account<input placeholder="Company or organization ID" value={form.external_account} onChange={(event) => setForm({ ...form, external_account: event.target.value })} /></label><label>Secret reference<input required placeholder="env:ACCOUNTING_TOKEN" value={form.credentials_ref} onChange={(event) => setForm({ ...form, credentials_ref: event.target.value })} /></label><button className="button">Connect</button></form></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Connections</p><h3>Provider status</h3></div></div><div className="integration-list">{connections.map((item) => <article className="integration-card" key={item.id}><div><strong>{item.name}</strong><span>{item.provider} · {item.external_account || 'No account selected'}</span><small>{item.credentials_ref} · Last sync {item.last_sync_at ? new Date(item.last_sync_at).toLocaleString() : 'never'}</small></div><div className="integration-actions"><b>{item.status}</b><button className="button-link" onClick={() => toggle(item)}>{item.is_enabled ? 'Disable' : 'Enable'}</button><button className="button button-small" disabled={!item.is_enabled} onClick={() => sync(item)}>Sync invoices</button></div></article>)}</div></section></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Reconciliation trail</p><h3>Recent sync runs</h3></div></div>{runs.map((run) => <div className="sync-row" key={run.id}><span><strong>{run.provider} · {run.entity}</strong><small>{new Date(run.started_at).toLocaleString()} · {run.records_synced} records</small></span><b>{run.status}</b></div>)}</section>{(error || message) && <div className={error ? 'form-error' : 'success-message'}>{error || message}</div>}</AppShell>
}
