import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { getInventoryForecast } from '../lib/api'

export default function InventoryForecastPage() {
  const [items, setItems] = useState([]); const [horizon, setHorizon] = useState(30); const [seasonal, setSeasonal] = useState(1); const [leadTime, setLeadTime] = useState(14); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  async function load() { setLoading(true); setError(''); try { const result = await getInventoryForecast(horizon, seasonal, leadTime); setItems(result.items || []) } catch (err) { setError(err.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [horizon, seasonal, leadTime])
  return <AppShell title="Inventory forecasting" eyebrow="Demand, reorder automation & stockout risk"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Forecast controls</p><h3>{horizon}-day demand view</h3></div><span className="tag">{loading ? 'Updating…' : 'Ready'}</span></div><div className="mini-form"><label>Horizon<select value={horizon} onChange={(event) => setHorizon(Number(event.target.value))}><option value="30">30 days</option><option value="60">60 days</option><option value="90">90 days</option><option value="180">180 days</option></select></label><label>Seasonality<select value={seasonal} onChange={(event) => setSeasonal(Number(event.target.value))}><option value="0.75">Low season · 0.75×</option><option value="1">Normal · 1×</option><option value="1.25">Peak season · 1.25×</option><option value="1.5">High growth · 1.5×</option></select></label><label>Supplier lead time<input type="number" min="1" max="180" value={leadTime} onChange={(event) => setLeadTime(Number(event.target.value) || 1)} /></label></div><p className="muted-copy">Reorder quantity includes expected demand, supplier lead time, and safety stock.</p></section><section className="panel">{items.map((item) => <div className="order-meta" key={item.inventory_id}><span><strong>{item.product}</strong><small>Available {item.available_quantity} · Demand {item.forecast_demand} · Daily {item.average_daily_demand} · Projected {item.projected_quantity} · Safety {item.safety_stock}</small><small>{item.supplier || 'Supplier not assigned'} · Stockout estimate {item.days_until_stockout == null ? 'not expected' : `${item.days_until_stockout} days`}</small></span><b className={item.risk === 'Stockout risk' ? 'priority-urgent' : ''}>{item.risk} · Order {item.suggested_order_quantity}</b></div>)}{!items.length && <p className="muted-copy">No inventory forecast data yet.</p>}{error && <div className="form-error">{error}</div>}</section></AppShell>
}
