import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { getMobileWorkshopTasks, recordWorkshopMaterial, updateMobileWorkshopTask, uploadProductionTaskPhoto } from '../lib/api'

export default function MobileWorkshopPage() {
  const [tasks, setTasks] = useState([]); const [selected, setSelected] = useState(null); const [code, setCode] = useState(''); const [minutes, setMinutes] = useState(0); const [material, setMaterial] = useState({ inventory_id: '', quantity: 1, movement: 'issue' }); const [photo, setPhoto] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  async function load(scan = '') { const result = await getMobileWorkshopTasks(scan); setTasks(result.items || []); if (!selected && result.items?.[0]) setSelected(result.items[0]) }
  useEffect(() => { load().catch((err) => setError(err.message)) }, [])
  async function scan(event) { event.preventDefault(); try { await load(code); setMessage(code ? 'Matching workshop tasks loaded.' : 'All workshop tasks loaded.'); setError('') } catch (err) { setError(err.message) } }
  async function update(status) { if (!selected) return; try { const result = await updateMobileWorkshopTask(selected.id, { status, actual_minutes: Number(minutes) || 0 }); setSelected(result.item); setTasks((items) => items.map((item) => item.id === result.item.id ? result.item : item)); setMessage(result.mode === 'demo' ? 'Saved locally for demo mode.' : `Task marked ${status.toLowerCase()}.`); setError('') } catch (err) { setError(err.message) } }
  async function movement(event) { event.preventDefault(); if (!selected) return; try { const result = await recordWorkshopMaterial(selected.id, { ...material, inventory_id: Number(material.inventory_id), quantity: Number(material.quantity) }); setSelected(result.item); setMessage(result.mode === 'offline' ? 'Material movement queued offline.' : 'Material movement recorded.'); setError('') } catch (err) { setError(err.message) } }
  async function choosePhoto(event) { const file = event.target.files?.[0]; if (!file || !selected) return; try { const result = await uploadProductionTaskPhoto(file, selected.id); setPhoto(result.item.url); setMessage('Workshop photo captured.'); setError('') } catch (err) { setError(err.message) } }
  return <AppShell title="Mobile workshop execution" eyebrow="QR tasks, material issue/return & offline-ready updates"><section className="panel"><div className="field-toolbar"><span className="field-offline-chip">Offline-ready · sync when connected</span></div><form className="qr-form" onSubmit={scan}><input placeholder="Scan task ID, job number or task name" value={code} onChange={(event) => setCode(event.target.value)} /><button className="button button-small">Scan task</button></form></section><div className="field-layout"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Workshop queue</p><h3>{tasks.length} task(s)</h3></div></div><div className="field-visit-list">{tasks.map((item) => <button className={`field-visit ${selected?.id === item.id ? 'selected' : ''}`} key={item.id} onClick={() => { setSelected(item); setMinutes(item.actual_minutes || 0) }}><span><strong>{item.job_number} · {item.name}</strong><small>{item.stage} · {item.assigned_worker || 'Unassigned'} · {item.machine || 'No machine'}</small></span><b>{item.status}</b></button>)}</div>{!tasks.length && <p className="muted-copy">No workshop tasks match this scan.</p>}</section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Task console</p><h3>{selected?.name || 'Choose a task'}</h3></div></div>{selected ? <><p className="muted-copy">{selected.job_number} · {selected.stage} · {selected.assigned_worker || 'Worker unassigned'}</p><div className="field-actions"><button className="button-link" onClick={() => update('In progress')}>Start task</button><button className="button-link" onClick={() => update('Blocked')}>Block</button><button className="button-link" onClick={() => update('Complete')}>Complete</button></div><label>Actual minutes<input type="number" min="0" value={minutes} onChange={(event) => setMinutes(event.target.value)} /></label><form className="gps-row" onSubmit={movement}><input required placeholder="Inventory item ID / QR" value={material.inventory_id} onChange={(event) => setMaterial({ ...material, inventory_id: event.target.value })} /><input required type="number" min="0.01" step="0.01" value={material.quantity} onChange={(event) => setMaterial({ ...material, quantity: event.target.value })} /><select value={material.movement} onChange={(event) => setMaterial({ ...material, movement: event.target.value })}><option value="issue">Issue</option><option value="return">Return</option></select><button className="button button-small">Record material</button></form><label>Task photo<input type="file" accept="image/*" capture="environment" onChange={choosePhoto} /></label>{photo && <img className="proof-preview" src={photo} alt="Workshop task proof" />}</> : <p className="muted-copy">Scan a QR/task code or select a task.</p>}</section></div>{(error || message) && <div className={error ? 'form-error' : 'success-message'}>{error || message}</div>}</AppShell>
}
