import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { downloadPaymentReceipt, getInvoices, getPaymentReconciliations, reconcilePayment, refundReconciledPayment } from '../lib/api'
import { useAuth } from '../context/AuthContext'

export default function PaymentReconciliationPage() {
  const { user } = useAuth(); const canManage = ['admin', 'sales'].includes(user.role); const [items, setItems] = useState([]); const [invoices, setInvoices] = useState([]); const [showForm, setShowForm] = useState(false); const [error, setError] = useState(''); const [form, setForm] = useState({ invoice_id: '', provider: 'Stripe', external_id: '', amount: '', status: 'Paid', dispute_reason: '' })
  async function load() { const [reconciliationResult, invoiceResult] = await Promise.all([getPaymentReconciliations(), getInvoices()]); setItems(reconciliationResult.items || []); setInvoices(invoiceResult.items || []) }
  useEffect(() => { load().catch((err) => setError(err.message)) }, [])
  async function submit(event) { event.preventDefault(); try { await reconcilePayment(form); setShowForm(false); setForm({ invoice_id: '', provider: 'Stripe', external_id: '', amount: '', status: 'Paid', dispute_reason: '' }); await load() } catch (err) { setError(err.message) } }
  async function refund(item) { const amount = window.prompt(`Refund amount (max ₹${Number(item.refundable_amount).toLocaleString('en-IN')})`, String(item.refundable_amount)); if (!amount) return; try { await refundReconciledPayment(item.id, { amount }); await load() } catch (err) { setError(err.message) } }
  return <AppShell title="Payment reconciliation" eyebrow="Gateway settlement & refunds" actions={canManage && <button className="button button-small" onClick={() => setShowForm(!showForm)}>{showForm ? 'Close' : 'Reconcile payment'}</button>}>
    {showForm && <form className="panel customer-editor" onSubmit={submit}><div className="form-grid form-grid-3"><label>Invoice<select required value={form.invoice_id} onChange={(e) => setForm({ ...form, invoice_id: e.target.value })}><option value="">Choose invoice</option>{invoices.map((item) => <option value={item.id} key={item.id}>{item.invoice_number} · {item.customer} · ₹{Number(item.balance || 0).toLocaleString('en-IN')}</option>)}</select></label><label>Provider<select value={form.provider} onChange={(e) => setForm({ ...form, provider: e.target.value })}><option>Stripe</option><option>Razorpay</option><option>Bank transfer</option><option>Manual</option></select></label><label>Transaction ID<input required value={form.external_id} onChange={(e) => setForm({ ...form, external_id: e.target.value })} placeholder="pi_... / pay_... / NEFT..." /></label><label>Amount<input required type="number" min="0.01" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></label><label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option>Paid</option><option>Failed</option><option>Disputed</option></select></label><label>Dispute reason<input value={form.dispute_reason} onChange={(e) => setForm({ ...form, dispute_reason: e.target.value })} /></label></div>{error && <div className="form-error">{error}</div>}<button className="button">Save reconciliation</button></form>}
    {error && !showForm && <div className="form-error">{error}</div>}<section className="reconciliation-grid">{items.map((item) => <article className="panel reconciliation-card" key={item.id}><div className="panel-heading"><div><p className="eyebrow">{item.invoice_number} · {item.provider}</p><h3>{item.customer}</h3></div><span className={`status status-${item.status.toLowerCase()}`}>{item.status}</span></div><div className="invoice-total"><div><span>Received</span><strong>₹{Number(item.amount).toLocaleString('en-IN')}</strong></div><div><span>Refundable</span><strong>₹{Number(item.refundable_amount).toLocaleString('en-IN')}</strong></div></div><div className="reconciliation-meta"><span>{item.external_id}</span><span>{item.refund_status}</span></div>{item.dispute_reason && <p className="form-error">Dispute: {item.dispute_reason}</p>}<div className="card-actions"><button className="button-link" onClick={() => downloadPaymentReceipt(item.id, item.invoice_number)}>Receipt</button>{canManage && Number(item.refundable_amount) > 0 && item.status === 'Paid' && <button className="button button-ghost" onClick={() => refund(item)}>Issue refund</button>}</div></article>)}</section>
  </AppShell>
}
