import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { createPurchaseOrder, createPurchaseOrderFromPlanning, createSupplier, getBusinessPlanning, getProducts, getPurchaseOrders, getSupplierPerformance, getSuppliers, updatePurchaseOrder } from '../lib/api'
import { useAuth } from '../context/AuthContext'

function LegacyProcurementPage() {
  const { user } = useAuth(); const canEdit = ['admin', 'sales'].includes(user.role); const canCreateSupplier = user.role === 'admin'
  const [suppliers, setSuppliers] = useState([]); const [orders, setOrders] = useState([]); const [products, setProducts] = useState([]); const [showSupplier, setShowSupplier] = useState(false); const [showOrder, setShowOrder] = useState(false); const [supplierForm, setSupplierForm] = useState({ name: '', email: '', phone: '', notes: '' }); const [form, setForm] = useState({ supplier_id: '', expected_date: '', product_id: '', quantity: 1, unit_cost: 0, notes: '' }); const [error, setError] = useState('')
  async function load() { setSuppliers((await getSuppliers()).items || []); setOrders((await getPurchaseOrders()).items || []); if (canEdit) setProducts((await getProducts()).items || []) }
  useEffect(() => { load() }, [])
  async function addSupplier(e) { e.preventDefault(); try { await createSupplier(supplierForm); setSupplierForm({ name: '', email: '', phone: '', notes: '' }); setShowSupplier(false); await load() } catch (err) { setError(err.message) } }
  async function addOrder(e) { e.preventDefault(); try { await createPurchaseOrder({ supplier_id: form.supplier_id, expected_date: form.expected_date, notes: form.notes, items: [{ product_id: form.product_id, quantity: form.quantity, unit_cost: form.unit_cost }] }); setShowOrder(false); await load() } catch (err) { setError(err.message) } }
  return <AppShell title="Procurement" eyebrow="Suppliers & purchasing" actions={canEdit && <><button className="button button-small" onClick={() => setShowOrder(!showOrder)}>{showOrder ? 'Close order' : 'New purchase order'}</button>{canCreateSupplier && <button className="button button-small button-ghost" onClick={() => setShowSupplier(!showSupplier)}>New supplier</button>}</>}>
    {error && <div className="form-error">{error}</div>}
    {showSupplier && <form className="panel customer-editor" onSubmit={addSupplier}><div className="panel-heading"><h3>Add supplier</h3></div><div className="form-grid form-grid-3"><label>Name<input required value={supplierForm.name} onChange={(e) => setSupplierForm({ ...supplierForm, name: e.target.value })} /></label><label>Email<input value={supplierForm.email} onChange={(e) => setSupplierForm({ ...supplierForm, email: e.target.value })} /></label><label>Phone<input value={supplierForm.phone} onChange={(e) => setSupplierForm({ ...supplierForm, phone: e.target.value })} /></label></div><button className="button">Save supplier</button></form>}
    {showOrder && <form className="panel customer-editor" onSubmit={addOrder}><div className="panel-heading"><h3>Create purchase order</h3></div><div className="form-grid form-grid-3"><label>Supplier<select required value={form.supplier_id} onChange={(e) => setForm({ ...form, supplier_id: e.target.value })}><option value="">Choose supplier</option>{suppliers.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Product<select required value={form.product_id} onChange={(e) => setForm({ ...form, product_id: e.target.value })}><option value="">Choose product</option>{products.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Quantity<input type="number" min="1" value={form.quantity} onChange={(e) => setForm({ ...form, quantity: e.target.value })} /></label><label>Unit cost<input type="number" min="0" value={form.unit_cost} onChange={(e) => setForm({ ...form, unit_cost: e.target.value })} /></label><label>Expected date<input type="date" value={form.expected_date} onChange={(e) => setForm({ ...form, expected_date: e.target.value })} /></label></div><button className="button">Create PO</button></form>}
    <section className="supplier-grid">{suppliers.map((item) => <article className="panel supplier-card" key={item.id}><p className="eyebrow">Supplier</p><h3>{item.name}</h3><p>{item.email || 'No email'} · {item.phone || 'No phone'}</p></article>)}</section>
    <section className="procurement-list">{orders.map((order) => <article className="panel procurement-card" key={order.id}><div className="panel-heading"><div><p className="eyebrow">{order.po_number} · {order.order_date}</p><h3>{order.supplier}</h3></div>{canEdit ? <select value={order.status} onChange={(e) => updatePurchaseOrder(order.id, { status: e.target.value }).then(load)}><option>Draft</option><option>Confirmed</option><option>Received</option><option>Cancelled</option></select> : <span className="status status-approved">{order.status}</span>}</div><div className="order-meta"><span>{order.items?.length || 0} items</span><strong>₹{Number(order.total || 0).toLocaleString('en-IN')}</strong><span>Expected {order.expected_date || '—'}</span></div></article>)}</section>
  </AppShell>
}

function ProcurementAutomationPanel() {
  const { user } = useAuth()
  const [suggestions, setSuggestions] = useState([]); const [suppliers, setSuppliers] = useState([]); const [performance, setPerformance] = useState([]); const [supplierId, setSupplierId] = useState(''); const [message, setMessage] = useState('')
  useEffect(() => { Promise.all([getBusinessPlanning(), getSuppliers(), getSupplierPerformance()]).then(([planning, supplierResult, performanceResult]) => { setSuggestions((planning.planning?.purchase_suggestions || []).filter((item) => Number(item.shortage_quantity) > 0)); setSuppliers(supplierResult.items || []); setPerformance(performanceResult.items || []) }) }, [])
  async function createFromPlanning() { if (!supplierId || !suggestions.length) return setMessage('Choose a supplier and ensure planning has shortages.'); await createPurchaseOrderFromPlanning({ supplier_id: Number(supplierId), items: suggestions, notes: 'Created from planning shortage suggestions.' }); setMessage('Purchase order created from shortage suggestions.') }
  if (user.role !== 'admin') return null
  return <section className="panel procurement-automation-panel"><div className="panel-heading"><div><p className="eyebrow">Automation</p><h3>Planning shortage → purchase order</h3></div></div><div className="order-meta"><span>{suggestions.length} shortage item(s) ready</span><select value={supplierId} onChange={(event) => setSupplierId(event.target.value)}><option value="">Choose supplier</option>{suppliers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="button button-small" onClick={createFromPlanning}>Create PO</button></div><p className="muted-copy">{performance.slice(0, 3).map((item) => `${item.supplier}: ${item.orders} orders · ${item.on_time_rate}% on time`).join(' · ') || 'Supplier performance will appear after purchase orders are tracked.'}</p>{message && <div className="success-message">{message}</div>}</section>
}

export default function ProcurementPage() { return <><LegacyProcurementPage /><ProcurementAutomationPanel /></> }
