import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { createProductionJob, getOrders, getProducts, getProductionJobs, handoffProductionJob, updateProductionJob } from '../lib/api'

const blankLine = { product_id: '', description: '', quantity: 1, unit: 'piece', wastage_percent: 5 }

export default function ProductionPage() {
  const [jobs, setJobs] = useState([]); const [orders, setOrders] = useState([]); const [products, setProducts] = useState([]); const [showForm, setShowForm] = useState(false); const [error, setError] = useState(''); const [form, setForm] = useState({ order_id: '', scheduled_start: '', due_date: '', assigned_team: '', wastage_percent: 5, notes: '', bom_items: [{ ...blankLine }] })
  async function load() { const [jobResult, orderResult, productResult] = await Promise.all([getProductionJobs(), getOrders(), getProducts()]); setJobs(jobResult.items || []); setOrders(orderResult.items || []); setProducts(productResult.items || []) }
  useEffect(() => { load().catch((err) => setError(err.message)) }, [])
  function setLine(index, changes) { setForm({ ...form, bom_items: form.bom_items.map((line, lineIndex) => lineIndex === index ? { ...line, ...changes } : line) }) }
  function chooseProduct(index, value) { const product = products.find((item) => Number(item.id) === Number(value)); setLine(index, { product_id: value, description: product?.name || '', unit: product?.unit || 'piece' }) }
  async function submit(event) { event.preventDefault(); setError(''); try { await createProductionJob(form); setShowForm(false); setForm({ order_id: '', scheduled_start: '', due_date: '', assigned_team: '', wastage_percent: 5, notes: '', bom_items: [{ ...blankLine }] }); await load() } catch (err) { setError(err.message) } }
  async function status(job, value) { try { await updateProductionJob(job.id, { status: value }); await load() } catch (err) { setError(err.message) } }
  async function handoff(job) { setError(''); try { await handoffProductionJob(job.id); await load() } catch (err) { setError(err.message) } }
  return <AppShell title="Production planning" eyebrow="Job cards & bills of materials" actions={<button className="button button-small" onClick={() => setShowForm(!showForm)}>{showForm ? 'Close' : 'New job card'}</button>}>
    {showForm && <form className="panel production-editor" onSubmit={submit}><div className="panel-heading"><div><p className="eyebrow">From an approved order</p><h3>Create production job</h3></div></div><div className="form-grid form-grid-3"><label>Order<select required value={form.order_id} onChange={(e) => setForm({ ...form, order_id: e.target.value })}><option value="">Choose order</option>{orders.map((item) => <option value={item.id} key={item.id}>{item.order_number} · {item.customer}</option>)}</select></label><label>Start date<input type="date" value={form.scheduled_start} onChange={(e) => setForm({ ...form, scheduled_start: e.target.value })} /></label><label>Due date<input type="date" value={form.due_date} onChange={(e) => setForm({ ...form, due_date: e.target.value })} /></label><label>Assigned team<input value={form.assigned_team} onChange={(e) => setForm({ ...form, assigned_team: e.target.value })} placeholder="Workshop team" /></label><label>Default wastage %<input type="number" min="0" max="100" value={form.wastage_percent} onChange={(e) => setForm({ ...form, wastage_percent: e.target.value })} /></label><label>Notes<input value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label></div><div className="bom-lines"><h4>Bill of materials</h4>{form.bom_items.map((line, index) => <div className="bom-line" key={index}><select required value={line.product_id} onChange={(e) => chooseProduct(index, e.target.value)}><option value="">Material / product</option>{products.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><input required value={line.description} onChange={(e) => setLine(index, { description: e.target.value })} placeholder="Description" /><input type="number" min="0.01" step="0.01" value={line.quantity} onChange={(e) => setLine(index, { quantity: e.target.value })} placeholder="Qty" /><input value={line.unit} onChange={(e) => setLine(index, { unit: e.target.value })} placeholder="Unit" /><input type="number" min="0" value={line.wastage_percent} onChange={(e) => setLine(index, { wastage_percent: e.target.value })} placeholder="Waste %" />{form.bom_items.length > 1 && <button type="button" className="button-link danger-link" onClick={() => setForm({ ...form, bom_items: form.bom_items.filter((_, lineIndex) => lineIndex !== index) })}>Remove</button>}</div>)}</div><div className="configurator-actions"><button type="button" className="button button-ghost" onClick={() => setForm({ ...form, bom_items: [...form.bom_items, { ...blankLine, wastage_percent: form.wastage_percent }] })}>+ Add material</button><button className="button">Create job card</button></div>{error && <div className="form-error">{error}</div>}</form>}
    {error && !showForm && <div className="form-error">{error}</div>}<section className="production-grid">{jobs.map((job) => <article className="panel production-card" key={job.id}><div className="panel-heading"><div><p className="eyebrow">{job.job_number} · {job.order_number}</p><h3>{job.customer}</h3></div><select value={job.status} onChange={(e) => status(job, e.target.value)}><option>Planned</option><option>Cutting</option><option>Assembly</option><option>Quality check</option><option>Ready</option><option>Complete</option><option>On hold</option></select></div><div className="production-meta"><span>{job.assigned_team || 'Unassigned'}</span><span>{job.due_date ? `Due ${job.due_date}` : 'No due date'}</span><span>{job.handoff ? 'Ready for delivery' : 'Production handoff pending'}</span></div><div className="bom-list">{(job.bom_items || []).map((item) => <div className="bom-item" key={item.id}><span>{item.description}<small>{item.quantity} {item.unit} + {item.wastage_percent}% waste</small></span><strong>{Number(item.planned_quantity || item.quantity).toFixed(2)}</strong></div>)}</div>{!job.handoff && (job.status === 'Ready' || job.status === 'Complete') && <div className="configurator-actions"><button type="button" className="button button-ghost button-small" onClick={() => handoff(job)}>Ready for delivery</button></div>}</article>)}</section>
  </AppShell>
}
