import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { createProductionTask, getProductionCapacity, getProductionJobs, getProductionSchedule } from '../lib/api'

export default function ProductionSchedulingPage() {
  const [tasks, setTasks] = useState([]); const [jobs, setJobs] = useState([]); const [capacity, setCapacity] = useState({}); const [form, setForm] = useState({ production_job_id: '', name: '', stage: 'Assembly', assigned_worker: '', machine: '', planned_start: '', planned_end: '' }); const [message, setMessage] = useState('')
  async function load() { const [schedule, jobResult, capacityResult] = await Promise.all([getProductionSchedule(), getProductionJobs(), getProductionCapacity()]); setTasks(schedule.items || []); setJobs(jobResult.items || []); setCapacity(capacityResult.capacity || {}) }
  useEffect(() => { load() }, [])
  async function submit(event) { event.preventDefault(); await createProductionTask({ ...form, production_job_id: Number(form.production_job_id) }); setForm({ ...form, name: '', planned_start: '', planned_end: '' }); setMessage('Production task scheduled.'); await load() }
  return <AppShell title="Advanced production scheduling" eyebrow="Capacity, dependencies & deadline alerts"><section className="metrics-grid"><article className="metric-card"><span>Planned tasks</span><strong>{capacity.planned_tasks || 0}</strong></article><article className="metric-card"><span>Open tasks</span><strong>{capacity.open_tasks || 0}</strong></article><article className="metric-card"><span>Deadline alerts</span><strong>{capacity.alert_count || 0}</strong></article></section><section className="panel"><form className="mini-form" onSubmit={submit}><select required value={form.production_job_id} onChange={(event) => setForm({ ...form, production_job_id: event.target.value })}><option value="">Choose job</option>{jobs.map((item) => <option key={item.id} value={item.id}>{item.job_number} · {item.customer}</option>)}</select><input required placeholder="Task name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><input placeholder="Worker" value={form.assigned_worker} onChange={(event) => setForm({ ...form, assigned_worker: event.target.value })} /><input placeholder="Machine" value={form.machine} onChange={(event) => setForm({ ...form, machine: event.target.value })} /><button className="button">Schedule task</button></form></section><section className="panel"><div className="panel-heading"><h3>Workshop calendar</h3></div>{tasks.map((task) => <div className="order-meta" key={task.id}><span><strong>{task.job_number} · {task.name}</strong><small>{task.assigned_worker || 'Worker unassigned'} · {task.machine || 'Machine unassigned'} · {task.stage}</small></span><b>{task.status}</b></div>)}{!tasks.length && <p className="muted-copy">No tasks scheduled yet.</p>}{message && <div className="success-message">{message}</div>}</section></AppShell>
}
