import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { getProductionCapacity, getProductionSchedule, updateProductionTask } from '../lib/api'

export default function ProductionGanttPage() {
  const [tasks, setTasks] = useState([]); const [capacity, setCapacity] = useState({}); const [conflicts, setConflicts] = useState([]); const [dragged, setDragged] = useState(null); const [message, setMessage] = useState('')
  async function load() { const [schedule, result] = await Promise.all([getProductionSchedule(), getProductionCapacity()]); setTasks(schedule.items || []); setConflicts(schedule.conflicts || []); setCapacity(result.capacity || {}) }
  useEffect(() => { load().catch((error) => setMessage(error.message)) }, [])
  async function drop(target) { if (!dragged || dragged.id === target.id) return; try { const result = await updateProductionTask(dragged.id, { dependency_id: target.id }); setMessage(result.conflicts?.length ? `${dragged.name} moved with ${result.conflicts.length} resource conflict(s) to review.` : `${dragged.name} now follows ${target.name}.`); setDragged(null); await load() } catch (error) { setMessage(error.message) } }
  const conflictIds = new Set(conflicts.flatMap((item) => [item.task_id, ...(item.conflicts || []).map((entry) => entry.task_id)]))
  return <AppShell title="Drag-and-drop production planner" eyebrow="Gantt dependencies & workshop capacity"><section className="metrics-grid"><article className="metric-card"><span>Open tasks</span><strong>{capacity.open_tasks || 0}</strong></article><article className="metric-card"><span>Worker minutes</span><strong>{Object.values(capacity.worker_minutes || {}).reduce((a, b) => a + b, 0)}</strong></article><article className="metric-card"><span>Deadline alerts</span><strong>{capacity.alert_count || 0}</strong></article><article className="metric-card"><span>Resource conflicts</span><strong>{conflicts.length}</strong></article></section><section className="panel"><p className="muted-copy">Drag a task onto another task to create a dependency. Resource overlaps are flagged when a worker or machine is scheduled at the same time.</p><div className="gantt-list">{tasks.map((task) => <div className={`gantt-row ${conflictIds.has(task.id) ? 'is-conflict' : ''}`} draggable onDragStart={() => setDragged(task)} onDragOver={(e) => e.preventDefault()} onDrop={() => drop(task)} key={task.id}><div><strong>{task.name}</strong><small>{task.job_number || 'Production job'} · {task.stage} · {task.assigned_worker || 'Unassigned'} · {task.machine || 'No machine'}</small></div><span className="gantt-bar" style={{ width: `${Math.max(24, Math.min(100, 24 + Number(task.actual_minutes || 0) / 4))}%` }}>{task.status}</span></div>)}{!tasks.length && <p className="muted-copy">No scheduled tasks yet.</p>}{message && <div className="success-message">{message}</div>}</div></section></AppShell>
}
