import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { createSupportTicket, downloadContractPdf, getProjectPortal } from '../lib/api'

export default function ProjectPortalPage() {
  const [portal, setPortal] = useState({ projects: [], documents: [], support_tickets: [] }); const [showForm, setShowForm] = useState(false); const [error, setError] = useState(''); const [form, setForm] = useState({ order_id: '', subject: '', message: '' })
  async function load() { setPortal(await getProjectPortal()) }
  useEffect(() => { load().catch((err) => setError(err.message)) }, [])
  async function submit(event) { event.preventDefault(); try { await createSupportTicket(form); setShowForm(false); setForm({ order_id: '', subject: '', message: '' }); await load() } catch (err) { setError(err.message) } }
  return <AppShell title="My project portal" eyebrow="Progress, documents & support" actions={<button className="button button-small" onClick={() => setShowForm(!showForm)}>{showForm ? 'Close' : 'Contact Furnivo'}</button>}>
    {showForm && <form className="panel customer-editor" onSubmit={submit}><h3>Project support request</h3><div className="form-grid form-grid-3"><label>Project<select required value={form.order_id} onChange={(e) => setForm({ ...form, order_id: e.target.value })}><option value="">Choose project</option>{portal.projects.map((project) => <option value={project.order.id} key={project.order.id}>{project.order.order_number} · {project.order.customer}</option>)}</select></label><label>Subject<input required value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} /></label><label className="form-span-3">Message<textarea required rows="4" value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} /></label></div>{error && <div className="form-error">{error}</div>}<button className="button">Send request</button></form>}
    {error && !showForm && <div className="form-error">{error}</div>}<section className="portal-project-grid">{portal.projects.map((project) => <article className="panel portal-project-card" key={project.order.id}><div className="panel-heading"><div><p className="eyebrow">{project.order.order_number}</p><h3>{project.order.customer}</h3></div><span className="status status-approved">{project.order.status}</span></div><div className="portal-progress"><div><span>Production</span><strong>{project.production?.status || project.order.production_status}</strong></div><div><span>Installation</span><strong>{project.order.installation_status}</strong></div><div><span>Payment</span><strong>{project.invoice?.status || 'Not invoiced'}</strong></div></div><h4>Upcoming schedule</h4>{project.schedules?.length ? project.schedules.map((schedule) => <div className="portal-schedule" key={schedule.id}><span>{schedule.schedule_type}<small>{schedule.assigned_team}</small></span><strong>{schedule.scheduled_date}</strong></div>) : <p className="muted-copy">No delivery or installation slot scheduled yet.</p>}<h4>Project timeline</h4>{project.timeline?.length ? <div className="portal-timeline">{project.timeline.slice(0, 8).map((event, index) => <div className="portal-timeline-item" key={`${event.type}-${event.date}-${index}`}><span className="timeline-dot" /><div><strong>{event.label} · {event.status}</strong><small>{event.detail}</small><small>{event.date ? new Date(event.date).toLocaleDateString() : ''}</small></div></div>)}</div> : <p className="muted-copy">Your project team will post updates here.</p>}</article>)}</section>
    <section className="portal-lower-grid"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">Shared files</p><h3>Documents</h3></div></div>{portal.documents.map((document) => <div className="portal-document" key={`${document.type}-${document.number}`}><span><strong>{document.number}</strong><small>{document.type} · {document.status}</small></span>{document.type === 'Contract' && <button className="button-link" onClick={() => downloadContractPdf({ id: document.id, contract_number: document.number, title: document.number, terms: '' })}>Download</button>}</div>)}</article><article className="panel"><div className="panel-heading"><div><p className="eyebrow">Help desk</p><h3>Support requests</h3></div></div>{portal.support_tickets?.length ? portal.support_tickets.map((ticket) => <div className="portal-ticket" key={ticket.id}><strong>{ticket.subject}</strong><span>{ticket.status}</span><small>{ticket.message}</small>{ticket.response && <p>{ticket.response}</p>}</div>) : <p className="muted-copy">No support requests yet.</p>}</article></section>
  </AppShell>
}
