import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { createQualityInspection, getProductionInspections, getProductionJobs, uploadQualityInspectionPhoto } from '../lib/api'

export default function QualityControlPage() {
  const [jobs, setJobs] = useState([]); const [inspections, setInspections] = useState([]); const [form, setForm] = useState({ job_id: '', status: 'Passed', notes: '', defects: '', rework_cost: 0 }); const [photo, setPhoto] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  async function loadInspections(jobId) { if (!jobId) return setInspections([]); const result = await getProductionInspections(jobId); setInspections(result.items || []) }
  useEffect(() => { getProductionJobs().then((result) => setJobs(result.items || [])).catch((err) => setError(err.message)) }, [])
  async function submit(event) { event.preventDefault(); setError(''); try { const result = await createQualityInspection(form.job_id, { status: form.status, notes: form.notes, rework_cost: Number(form.rework_cost || 0), photo_url: photo, checklist: [{ item: 'Dimensions and finish', passed: form.status === 'Passed' }, { item: 'Packaging and fittings', passed: form.status === 'Passed' }], defects: form.defects ? [form.defects] : [] }); setMessage(result.mode === 'demo' ? 'Inspection saved in demo mode.' : 'Quality inspection recorded.'); setForm({ ...form, notes: '', defects: '', rework_cost: 0 }); setInspections((items) => [result.item, ...items]) } catch (err) { setError(err.message) } }
  async function choosePhoto(event) { const file = event.target.files?.[0]; if (!file) return; try { const result = await uploadQualityInspectionPhoto(file, 'pending'); setPhoto(result.item.url); setMessage('Inspection evidence photo ready.'); setError('') } catch (err) { setError(err.message) } }
  return <AppShell title="Quality control" eyebrow="Inspections, defects & approval gates"><section className="panel"><p className="muted-copy">Production cannot be marked complete until a Passed inspection exists. Failed and Rework results remain visible for corrective action.</p><form className="service-form" onSubmit={submit}><label>Production job<select required value={form.job_id} onChange={(event) => { setForm({ ...form, job_id: event.target.value }); loadInspections(event.target.value) }}><option value="">Choose job</option>{jobs.map((item) => <option key={item.id} value={item.id}>{item.job_number} · {item.customer}</option>)}</select></label><label>Inspection result<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option>Passed</option><option>Failed</option><option>Rework</option><option>Pending</option></select></label><label>Defect or rework note<input value={form.defects} onChange={(event) => setForm({ ...form, defects: event.target.value })} /></label><label>Rework cost<input type="number" min="0" value={form.rework_cost} onChange={(event) => setForm({ ...form, rework_cost: event.target.value })} /></label><label>Inspection evidence<input type="file" accept="image/*" onChange={choosePhoto} /></label><label>Inspection notes<textarea rows="3" value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label><button className="button">Record inspection</button></form>{photo && <img className="proof-preview" src={photo} alt="Inspection evidence" />}{(error || message) && <div className={error ? 'form-error' : 'success-message'}>{error || message}</div>}</section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Audit trail</p><h3>Recent inspections</h3></div></div>{inspections.map((item) => <div className="order-meta" key={item.id}><span><strong>{item.status}</strong><small>{item.notes || 'No notes'} · Defects {(item.defects || []).length} · Rework ₹{Number(item.rework_cost || 0).toLocaleString('en-IN')}</small></span><b>{item.approved_at ? 'Approved gate' : 'Needs action'}</b></div>)}{!inspections.length && <p className="muted-copy">Select a job to view its inspection history.</p>}</section></AppShell>
}
