import { useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { resetPassword } from '../lib/api'

export default function ResetPasswordPage() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const [token, setToken] = useState(params.get('token') || ''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  async function submit(event) { event.preventDefault(); setError(''); if (password !== confirm) { setError('Passwords do not match.'); return } setLoading(true); try { await resetPassword(token, password); navigate('/login?reset=success') } catch (err) { setError(err.message || 'Unable to reset password.') } finally { setLoading(false) } }
  return <div className="login-layout"><section className="login-story"><Link className="brand brand-light" to="/"><span className="brand-mark brand-mark-light">F</span><span>Furnivo</span></Link><div className="login-story-copy"><p className="eyebrow eyebrow-light">Secure reset</p><h1>Choose a password your future self will thank you for.</h1><p>Use at least 10 characters with uppercase, lowercase and a number.</p></div></section><section className="login-panel"><form className="login-card" onSubmit={submit}><Link className="back-link" to="/login">← Back to sign in</Link><div className="login-heading"><p className="eyebrow">New password</p><h2>Set a new password</h2></div><label>Reset token<input value={token} onChange={(event) => setToken(event.target.value)} required /></label><label>New password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} minLength={10} required /></label><label>Confirm password<input type="password" value={confirm} onChange={(event) => setConfirm(event.target.value)} minLength={10} required /></label>{error && <div className="form-error">{error}</div>}<button className="button login-button" disabled={loading}>{loading ? 'Updating…' : 'Update password'}</button></form></section></div>
}
