import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { disableMfa, enableMfa, getSecurityStatus, revokeAllSessions } from '../lib/api'

export default function SecurityPage() {
  const [security, setSecurity] = useState({ mfa_enabled: false, sessions: [] }); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  async function load() { setSecurity(await getSecurityStatus()) }
  useEffect(() => { load().catch((err) => setError(err.message)) }, [])
  async function action(fn, text) { setError(''); try { await fn(); setMessage(text); await load() } catch (err) { setError(err.message) } }
  return <AppShell title="Security settings" eyebrow="Sessions, MFA & access controls"><section className="security-grid"><article className="panel security-card"><p className="eyebrow">Multi-factor authentication</p><h3>{security.mfa_enabled ? 'MFA is enabled' : 'MFA is not enabled'}</h3><p className="muted-copy">Protect sign-ins with a time-limited one-time code challenge.</p><button className="button button-small" onClick={() => action(security.mfa_enabled ? disableMfa : enableMfa, security.mfa_enabled ? 'MFA disabled.' : 'MFA enabled.')}>{security.mfa_enabled ? 'Disable MFA' : 'Enable MFA'}</button></article><article className="panel security-card"><p className="eyebrow">Session control</p><h3>{security.sessions?.filter((session) => !session.revoked).length || 0} active sessions</h3><p className="muted-copy">Rotate refresh tokens and invalidate all current sessions if access is suspected.</p><button className="button button-ghost button-small" onClick={() => action(revokeAllSessions, 'All sessions revoked. Sign in again on trusted devices.')}>Revoke all sessions</button></article></section>{(error || message) && <div className={error ? 'form-error' : 'success-message'}>{error || message}</div>}<section className="panel history-panel"><div className="panel-heading"><div><p className="eyebrow">Recent sessions</p><h3>Session history</h3></div></div>{security.sessions?.length ? security.sessions.map((session) => <div className="session-row" key={session.id}><span><strong>{session.user_agent || 'Unknown browser'}</strong><small>{session.ip_address || 'Unknown IP'} · Created {new Date(session.created_at).toLocaleString()}</small></span><b>{session.revoked ? 'Revoked' : 'Active'}</b></div>) : <p className="muted-copy">No session records yet.</p>}</section></AppShell>
}
