import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { getAccessUsers, getStaffInvitations, inviteStaff, updateStaff } from '../lib/api'

const roles = ['sales', 'designer', 'workshop_operator', 'installer', 'accountant']
const label = (role) => String(role || '').replaceAll('_', ' ')

export default function StaffManagementPage() {
  const [users, setUsers] = useState([]); const [invitations, setInvitations] = useState([]); const [form, setForm] = useState({ name: '', email: '', role: 'sales' }); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  async function load() { const [access, inviteData] = await Promise.all([getAccessUsers(), getStaffInvitations()]); setUsers(access.items || []); setInvitations(inviteData.items || []) }
  useEffect(() => { load().catch((err) => setError(err.message)) }, [])
  async function submit(event) { event.preventDefault(); try { const result = await inviteStaff(form); setInvitations((items) => [result.item, ...items]); setForm({ name: '', email: '', role: 'sales' }); setMessage(result.item.invite_token ? `Invite created. Demo token: ${result.item.invite_token}` : 'Invitation created. Share the secure invite link with the team member.'); setError('') } catch (err) { setError(err.message) } }
  async function toggle(user) { try { const result = await updateStaff(user.id, { is_active: user.is_active === false }); setUsers((items) => items.map((entry) => entry.user.id === user.id ? { ...entry, user: result.item } : entry)); setMessage('Staff account updated.'); setError('') } catch (err) { setError(err.message) } }
  return <AppShell title="Staff management" eyebrow="Invite users, roles & account status"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Secure onboarding</p><h3>Invite a staff member</h3></div><span className="mode-chip">Admin only</span></div><form className="mini-form staff-invite-form" onSubmit={submit}><input required placeholder="Full name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><input required type="email" placeholder="Work email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /><select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}>{roles.map((role) => <option key={role} value={role}>{label(role)}</option>)}</select><button className="button button-small">Create invitation</button></form>{(error || message) && <div className={error ? 'form-error' : 'success-message'}>{error || message}</div>}</section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Active workspace accounts</p><h3>People and role status</h3></div></div><div className="staff-list">{users.map((entry) => <div className="staff-row" key={entry.user.id}><span><strong>{entry.user.name}</strong><small>{entry.user.email} · {label(entry.user.role)}</small></span><div className="card-actions"><span className={`status ${entry.user.is_active === false ? 'status-rejected' : 'status-approved'}`}>{entry.user.is_active === false ? 'Inactive' : 'Active'}</span>{entry.user.role !== 'admin' && <button className="button-link" onClick={() => toggle(entry.user)}>{entry.user.is_active === false ? 'Activate' : 'Deactivate'}</button>}</div></div>)}</div></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Pending invitations</p><h3>Onboarding queue</h3></div></div>{invitations.length ? invitations.map((item) => <div className="invite-row" key={item.id}><span><strong>{item.name}</strong><small>{item.email} · {label(item.role)} · expires {new Date(item.expires_at).toLocaleDateString()}</small></span><b>{item.status}</b></div>) : <p className="muted-copy">No staff invitations yet.</p>}</section></AppShell>
}

