import { useEffect, useState } from 'react'
import AppShell from '../components/AppShell'
import { createWarehouse, getStockMovements, getWarehouseStock, getWarehouses, transferStock } from '../lib/api'
import { useAuth } from '../context/AuthContext'

export default function WarehousesPage() {
  const { user } = useAuth(); const canEdit = ['admin', 'sales'].includes(user.role); const canCreate = user.role === 'admin'; const [warehouses, setWarehouses] = useState([]); const [stock, setStock] = useState([]); const [movements, setMovements] = useState([]); const [showWarehouse, setShowWarehouse] = useState(false); const [showTransfer, setShowTransfer] = useState(false); const [warehouseForm, setWarehouseForm] = useState({ name: '', address: '', manager: '' }); const [transfer, setTransfer] = useState({ from_warehouse_id: '', to_warehouse_id: '', product_id: '', quantity: 1, reference: '' }); const [error, setError] = useState('')
  async function load() { setWarehouses((await getWarehouses()).items || []); setStock((await getWarehouseStock()).items || []); setMovements((await getStockMovements()).items || []) }
  useEffect(() => { load() }, [])
  async function addWarehouse(e) { e.preventDefault(); try { await createWarehouse(warehouseForm); setShowWarehouse(false); setWarehouseForm({ name: '', address: '', manager: '' }); await load() } catch (err) { setError(err.message) } }
  async function move(e) { e.preventDefault(); try { await transferStock(transfer); setShowTransfer(false); await load() } catch (err) { setError(err.message) } }
  const products = [...new Map(stock.map((item) => [item.product_id, item])).values()]
  return <AppShell title="Warehouses" eyebrow="Multi-location stock" actions={canEdit && <><button className="button button-small" onClick={() => setShowTransfer(!showTransfer)}>{showTransfer ? 'Close transfer' : 'Transfer stock'}</button>{canCreate && <button className="button button-small button-ghost" onClick={() => setShowWarehouse(!showWarehouse)}>New warehouse</button>}</>}>
    {error && <div className="form-error">{error}</div>}{showWarehouse && <form className="panel customer-editor" onSubmit={addWarehouse}><h3>Add warehouse</h3><div className="form-grid form-grid-3"><label>Name<input required value={warehouseForm.name} onChange={(e) => setWarehouseForm({ ...warehouseForm, name: e.target.value })} /></label><label>Address<input value={warehouseForm.address} onChange={(e) => setWarehouseForm({ ...warehouseForm, address: e.target.value })} /></label><label>Manager<input value={warehouseForm.manager} onChange={(e) => setWarehouseForm({ ...warehouseForm, manager: e.target.value })} /></label></div><button className="button">Save warehouse</button></form>}{showTransfer && <form className="panel customer-editor" onSubmit={move}><h3>Transfer stock</h3><div className="form-grid form-grid-3"><label>From<select required value={transfer.from_warehouse_id} onChange={(e) => setTransfer({ ...transfer, from_warehouse_id: e.target.value })}><option value="">Choose</option>{warehouses.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>To<select required value={transfer.to_warehouse_id} onChange={(e) => setTransfer({ ...transfer, to_warehouse_id: e.target.value })}><option value="">Choose</option>{warehouses.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Product<select required value={transfer.product_id} onChange={(e) => setTransfer({ ...transfer, product_id: e.target.value })}><option value="">Choose</option>{products.map((item) => <option value={item.product_id} key={item.product_id}>{item.product}</option>)}</select></label><label>Quantity<input type="number" min="1" value={transfer.quantity} onChange={(e) => setTransfer({ ...transfer, quantity: e.target.value })} /></label><label>Reference<input value={transfer.reference} onChange={(e) => setTransfer({ ...transfer, reference: e.target.value })} /></label></div><button className="button">Transfer</button></form>}
    <section className="warehouse-grid">{warehouses.map((item) => <article className="panel supplier-card" key={item.id}><p className="eyebrow">Warehouse</p><h3>{item.name}</h3><p>{item.address}</p><small>Manager: {item.manager}</small></article>)}</section><section className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>Warehouse</th><th>Product</th><th>SKU</th><th>Total</th><th>Reserved</th><th>Available</th></tr></thead><tbody>{stock.map((item) => <tr key={item.id}><td data-label="Warehouse">{item.warehouse}</td><td data-label="Product">{item.product}</td><td data-label="SKU">{item.sku}</td><td data-label="Total">{item.quantity}</td><td data-label="Reserved">{item.reserved_quantity}</td><td data-label="Available"><strong>{item.available_quantity}</strong></td></tr>)}</tbody></table></div></section><section className="panel history-panel"><div className="panel-heading"><h3>Recent movements</h3></div>{movements.map((item) => <div className="history-item" key={item.id}><strong>{item.product} · {item.quantity}</strong><span>{item.from_warehouse || 'Opening'} → {item.to_warehouse || 'Dispatch'}</span><small>{item.reference || 'No reference'}</small></div>)}</section>
  </AppShell>
}
